services:
  postgres:
    image: postgres:16-bookworm
    container_name: gpt_helper_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gpt_helper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: gpt_helper_postgres_data
        target: /var/lib/postgresql/data

volumes:
    gpt_helper_postgres_data:
